### ISSUE TITLE
Getting error while downloading module

### ISSUE THREAD

**Issue by shivam201312** [storj/storj#3053]
Hi...
I am getting error while running get command .
command :
```
go get storj.io/storj/lib/uplink
```
Error i am getting : 
```
go/src/github.com/zeebo/errs/errs.go:42:9: undefined: errors.Unwrap
go/src/github.com/zeebo/errs/group.go:84:6: undefined: errors.Is
```

**Comment by kaloyan-raev** [comment]
@shivam201312 did you try running `go get github.com/zeebo/errs`?

**Comment by shivam201312** [comment]
@kaloyan-raev  Yes i have tried running 
```go get github.com/zeebo/errs 
```
but getting same error .

**Comment by kaloyan-raev** [comment]
@shivam201312 It looks like the latest changes in github.com/zeebo/errs require go1.13. Try update to this version if you haven't done yet.

**Comment by littleskunk** [comment]
@kaloyan-raev negative. It doesn't work with go1.13

```
root@kali:~# go version
go version go1.13 linux/amd64
root@kali:~# go get storj.io/storj/lib/uplink
# storj.io/storj/pkg/ranger
go/src/storj.io/storj/pkg/ranger/common.go:11:13: undefined: errs.Class
# storj.io/storj/pkg/pkcrypto
go/src/storj.io/storj/pkg/pkcrypto/common.go:29:22: undefined: errs.Class
go/src/storj.io/storj/pkg/pkcrypto/common.go:31:13: undefined: errs.Class
go/src/storj.io/storj/pkg/pkcrypto/common.go:33:12: undefined: errs.Class
go/src/storj.io/storj/pkg/pkcrypto/common.go:35:23: undefined: errs.Class
go/src/storj.io/storj/pkg/pkcrypto/common.go:37:19: undefined: errs.Class
go/src/storj.io/storj/pkg/pkcrypto/encoding.go:114:10: undefined: errs.New
# storj.io/drpc
go/src/storj.io/drpc/drpc.go:14:18: undefined: errs.Class
go/src/storj.io/drpc/drpc.go:15:18: undefined: errs.Class
go/src/storj.io/drpc/drpc.go:16:18: undefined: errs.Class
# storj.io/storj/pkg/macaroon
go/src/storj.io/storj/pkg/macaroon/apikey.go:19:10: undefined: errs.Class
go/src/storj.io/storj/pkg/macaroon/apikey.go:21:14: undefined: errs.Class
go/src/storj.io/storj/pkg/macaroon/apikey.go:23:15: undefined: errs.Class
go/src/storj.io/storj/pkg/macaroon/apikey.go:25:20: undefined: errs.Class
go/src/storj.io/storj/pkg/macaroon/apikey.go:27:15: undefined: errs.Class
# storj.io/storj/storage
go/src/storj.io/storj/storage/blob.go:15:25: undefined: errs.Class
go/src/storj.io/storj/storage/common.go:21:22: undefined: errs.Class
go/src/storj.io/storj/storage/common.go:24:19: undefined: errs.Class
go/src/storj.io/storj/storage/common.go:27:23: undefined: errs.Class
go/src/storj.io/storj/storage/common.go:30:21: undefined: errs.Class
# storj.io/storj/internal/errs2
go/src/storj.io/storj/internal/errs2/ignore.go:18:9: undefined: errs.IsFunc
go/src/storj.io/storj/internal/errs2/rpc.go:14:9: undefined: errs.IsFunc
```

**Comment by thepaul** [comment]
Libuplink should build fine with Go 1.12, but you need to arrange for the module dependencies to be met using the Go modules functionality (`go mod download`, not `go get -u ./...` or the like). Otherwise you'll end up getting the wrong versions of the dependencies, and that will cause any number of problems.

**Comment by mahib480** [comment]
Hi, I am getting same error in golang. How can I resolve this error?
My golang version is 1.13 and I have also runned following command inside storj.io/storj directory 
```
go mod download 
```
